
-- Seed page_content with current static content from all public pages

INSERT INTO page_content (page_slug, section_key, content_value, is_active, ordem) VALUES

-- HOME
('home', 'hero', '{"badge":"Inteligência de Dados para Decisões Estratégicas","value_proposition":"Inteligência de dados e sistemas sob medida para organizações que buscam resultados mensuráveis.","cta_primary_text":"Falar com Especialista","cta_primary_link":"https://wa.me/5577991005071","cta_secondary_text":"Conhecer Serviços","cta_secondary_link":"/consultoria","trust_indicators":["100% Sigiloso","Resultados em Semanas","Equipe Especializada"],"messages":[{"headline":"Dados sem estratégia","highlight":"são apenas custo.","description":"Convertemos investimento em dados em vantagem competitiva mensurável.","style":"statement"},{"headline":"Sua diretoria decide com dados","highlight":"ou com opinião?","description":"Inteligência analítica que transforma reuniões de board em decisões precisas.","style":"question"},{"headline":"Não entregamos dashboards.","highlight":"Entregamos respostas.","description":"Do problema de negócio à solução implementada. Sem ruído, sem relatórios ignorados.","style":"statement"},{"headline":"Quanto sua operação perde","highlight":"por dia com processos manuais?","description":"Automação inteligente que libera sua equipe para o que realmente importa.","style":"question"},{"headline":"IA não é tendência.","highlight":"É infraestrutura.","description":"Machine Learning em produção, não em POCs que nunca saem do papel.","style":"statement"},{"headline":"Seu concorrente já automatizou.","highlight":"Qual é o seu plano?","description":"Consultoria estratégica para quem não pode esperar mais 2 anos.","style":"question"}]}'::jsonb, true, 1),

('home', 'worlds', '{"badge":"Soluções Integradas","title":"Três Dimensões de","title_highlight":"Inteligência Estratégica","description":"Ciência, engenharia e educação trabalhando juntas para transformar dados em vantagem competitiva sustentável.","bottom_cta_text":"Não sabe por onde começar? Nós ajudamos a identificar a melhor solução para seu contexto.","bottom_cta_button":"Agendar Diagnóstico Gratuito","bottom_cta_link":"/contato","items":[{"id":"ciencia","title":"Ciência de Dados & Inteligência","subtitle":"Para CEOs e diretores que precisam de decisões baseadas em evidências","description":"Transforme dados dispersos em insights acionáveis. Reduza o tempo de análise em até 80% e tome decisões com confiança estatística.","link":"/consultoria","result":"Decisões 3x mais rápidas com base em dados","features":["Machine Learning & IA Preditiva","Análise Bioestatística Avançada","Dashboards para C-Level","Customer & People Intelligence"],"stats_value":"80%","stats_label":"Redução em tempo de análise"},{"id":"engenharia","title":"Engenharia de Sistemas","subtitle":"Para operações que perdem horas com processos manuais","description":"Automatize fluxos repetitivos e libere sua equipe para atividades estratégicas. Sistemas que crescem junto com seu negócio.","link":"/sistemas","result":"Redução de 60% em tarefas operacionais","features":["Sistemas Sob Medida","Plataformas SaaS Escaláveis","Secretária Virtual com IA","APIs & Integrações Complexas"],"stats_value":"60%","stats_label":"Menos tarefas manuais"},{"id":"educacao","title":"Educação Corporativa","subtitle":"Para empresas que querem autonomia em dados","description":"Capacite sua equipe para interpretar dados e tomar decisões independentes. Cultura data-driven começa pelas pessoas.","link":"/educacao","result":"Maturidade analítica em 90 dias","features":["Diagnóstico de Maturidade","Capacitação Prática In Company","Formação de Lideranças","Preparação para Adoção de IA"],"stats_value":"90","stats_label":"Dias para maturidade"}]}'::jsonb, true, 2),

('home', 'about', '{"badge":"Como Trabalhamos","title":"Do problema à solução","title_highlight":"em 4 etapas","description":"Não entregamos apenas relatórios — implementamos soluções completas com impacto mensurável nos seus KPIs.","cta_primary_text":"Conheça Nossa História","cta_primary_link":"/sobre","cta_secondary_text":"Sobre o Fundador","cta_secondary_link":"/fundador","steps":[{"step":"01","title":"Diagnóstico","description":"Mapeamos o problema real com análise rigorosa — não o sintoma."},{"step":"02","title":"Solução","description":"Desenhamos a arquitetura específica para seu contexto e dados."},{"step":"03","title":"Implementação","description":"Desenvolvemos e colocamos em produção com entregas incrementais."},{"step":"04","title":"Transferência","description":"Capacitamos sua equipe para sustentar e evoluir o resultado."}]}'::jsonb, true, 3),

('home', 'results', '{"badge":"Resultados Documentados","title":"Impacto","title_highlight":"Mensurável","description":"Métricas baseadas em benchmarks de mercado e literatura científica. Resultados reais, não promessas genéricas.","footer_text":"Métricas baseadas em resultados reais de projetos entregues com acompanhamento pós-entrega documentado.","metrics":[{"metric":"80%","label":"Redução no Tempo de Análise","description":"Automação de processos analíticos que antes levavam dias","source":"Média em projetos de BI entregues pela Vixio"},{"metric":"3.2x","label":"ROI em Data Science","description":"Retorno médio documentado em projetos de ML em produção","source":"Média dos projetos Vixio com acompanhamento pós-entrega"},{"metric":"45%","label":"Melhoria na Precisão","description":"Acurácia em modelos preditivos vs. decisões baseadas em intuição","source":"Comparativo interno antes/depois em projetos Vixio"},{"metric":"60%","label":"Redução de Tarefas Manuais","description":"Liberação de equipes para atividades estratégicas","source":"Benchmark operacional médio dos clientes atendidos"}]}'::jsonb, true, 4),

('home', 'cta', '{"badge":"Comece Agora","title":"Pronto para","title_highlight":"resolver de verdade?","description":"Agende uma conversa sem compromisso. Em 30 minutos, entendemos seu desafio e mostramos como podemos ajudar.","cta_primary_text":"Agendar Conversa","cta_primary_link":"/contato","cta_secondary_text":"WhatsApp Direto","cta_secondary_link":"https://wa.me/5577991005071","guarantees":["Orçamento gratuito","Conversa 100% confidencial","Resposta em até 24h"],"steps":[{"title":"Conversa Inicial","description":"30 minutos para entender seu desafio","badge":"Gratuito"},{"title":"Proposta Técnica","description":"Escopo, prazo e investimento claros","badge":"Em 48h"},{"title":"Início do Projeto","description":"Kickoff e primeiras entregas","badge":"Em 1 semana"}]}'::jsonb, true, 5),

-- SOBRE
('sobre', 'hero', '{"badge":"Sobre a Vixio","title":"Transformando o futuro com","title_highlight":"tecnologia","description":"Somos uma empresa de tecnologia especializada em sistemas inteligentes e ciência de dados, dedicada a transformar desafios complexos em soluções inovadoras."}'::jsonb, true, 1),

('sobre', 'history', '{"title":"Nossa História","paragraphs":["A Vixio nasceu da paixão por transformar dados em soluções que geram valor real para as empresas. Fundada por profissionais com vasta experiência em pesquisa científica, desenvolvimento de software e gestão estratégica.","Ao longo dos anos, evoluímos de uma consultoria de desenvolvimento para uma empresa completa de tecnologia, atendendo desde startups até organizações públicas em suas jornadas de transformação digital.","Hoje, combinamos rigor acadêmico com agilidade de mercado para entregar sistemas inteligentes que geram impacto mensurável."],"timeline":[{"year":"2016","title":"Fundação","description":"Início das operações com foco em desenvolvimento web e soluções PHP para pequenas e médias empresas."},{"year":"2018","title":"Expansão para Dados","description":"Ampliação do portfólio para incluir análise de dados e Business Intelligence, atendendo demandas corporativas."},{"year":"2020","title":"IA & Machine Learning","description":"Entrada no mercado de Machine Learning e IA aplicada, com projetos em saúde pública e gestão estratégica."},{"year":"2022","title":"Consolidação","description":"Mais de 100 projetos entregues, expansão da equipe multidisciplinar e parcerias com instituições de ensino."},{"year":"2024","title":"Plataforma Completa","description":"Lançamento de soluções SaaS próprias e consolidação como referência em sistemas inteligentes e ciência de dados."}]}'::jsonb, true, 2),

('sobre', 'differentials', '{"badge":"Por que a Vixio","title":"Nossos Diferenciais","description":"O que nos torna a escolha certa para projetos de tecnologia e dados.","items":[{"title":"Equipe com DNA Científico","description":"Nossa equipe une formação acadêmica rigorosa (mestrados e doutorados) com experiência prática de mercado."},{"title":"Metodologia Proprietária","description":"Processo estruturado em 5 fases — Discovery, Exploration, Development, Production e Operations — garantindo entregas previsíveis."},{"title":"Foco em Resultados Mensuráveis","description":"Cada projeto é orientado por KPIs claros, com dashboards de acompanhamento em tempo real para o cliente."}]}'::jsonb, true, 3),

('sobre', 'mission_vision', '{"mission":{"title":"Missão","description":"Transformar dados em decisões estratégicas através de sistemas inteligentes e soluções tecnológicas inovadoras, impulsionando o crescimento sustentável de nossos clientes."},"vision":{"title":"Visão","description":"Ser reconhecida como a principal referência em sistemas inteligentes e ciência de dados no Brasil, liderando a transformação digital com soluções que fazem a diferença."}}'::jsonb, true, 4),

('sobre', 'values', '{"badge":"Nossos Valores","title":"O que nos move","description":"Princípios que guiam cada decisão e cada linha de código que escrevemos.","items":[{"title":"Inovação","description":"Buscamos constantemente as melhores tecnologias e metodologias para entregar soluções de ponta."},{"title":"Parceria","description":"Trabalhamos lado a lado com nossos clientes, construindo relacionamentos de longo prazo."},{"title":"Excelência","description":"Comprometimento com a qualidade em cada linha de código e cada entrega."},{"title":"Paixão","description":"Amamos o que fazemos e isso se reflete em cada projeto que desenvolvemos."}]}'::jsonb, true, 5),

('sobre', 'faq', '{"badge":"Dúvidas Frequentes","title":"Perguntas & Respostas","description":"Tudo o que você precisa saber antes de começar um projeto conosco.","items":[{"question":"Quais tipos de projetos a Vixio atende?","answer":"Atendemos desde startups que precisam de MVPs até grandes corporações com demandas complexas de ciência de dados, automação com IA, Business Intelligence, sistemas de gestão e plataformas SaaS."},{"question":"Qual é o prazo médio de entrega de um projeto?","answer":"Projetos menores levam de 2 a 4 semanas. Projetos de médio porte de 1 a 3 meses. Projetos complexos de 3 a 6 meses."},{"question":"Como funciona o processo de contratação?","answer":"Iniciamos com uma reunião de diagnóstico gratuita. Elaboramos uma proposta técnica detalhada. Após aprovação, o projeto segue nosso processo em 5 fases."},{"question":"A Vixio oferece suporte após a entrega?","answer":"Sim. Todos os projetos incluem suporte pós-entrega de 30 a 90 dias, além de planos de manutenção contínua."},{"question":"Vocês trabalham com dados sensíveis?","answer":"Sim. Seguimos criptografia, RBAC, ambientes isolados e conformidade com LGPD."},{"question":"Qual é o investimento mínimo?","answer":"Consultoria pontual a partir de R$ 5.000. Sistemas customizados a partir de R$ 15.000."},{"question":"Vocês atendem fora de Vitória da Conquista?","answer":"Sim. Atendemos em todo o Brasil de forma remota."},{"question":"Posso acompanhar o projeto em tempo real?","answer":"Sim. Cada cliente recebe acesso ao painel de acompanhamento com visibilidade sobre fases, entregas e prazos."}]}'::jsonb, true, 6),

-- SERVIÇOS
('servicos', 'hero', '{"badge":"Nossos Serviços","title":"Soluções completas em","title_highlight":"tecnologia","description":"Da análise à implementação, oferecemos expertise em todas as etapas da transformação digital da sua empresa."}'::jsonb, true, 1),

('servicos', 'cta', '{"title":"Pronto para começar seu projeto?","description":"Entre em contato e descubra como podemos ajudar sua empresa a alcançar novos patamares com tecnologia.","cta_primary_text":"Fale com um Especialista","cta_primary_link":"/contato","cta_secondary_text":"Ver Portfólio","cta_secondary_link":"/portfolio"}'::jsonb, true, 3),

-- CONTATO
('contato', 'hero', '{"badge":"Contato","title":"Vamos","title_highlight":"conversar","description":"Entre em contato e descubra como podemos ajudar sua empresa a alcançar novos patamares com tecnologia."}'::jsonb, true, 1),

('contato', 'info', '{"items":[{"title":"Email","value":"contato@vixio.com.br","link":"mailto:contato@vixio.com.br"},{"title":"Telefone","value":"+55 (77) 99100-5071","link":"tel:+5577991005071"},{"title":"Localização","value":"São Paulo, SP - Brasil","link":null},{"title":"Horário","value":"Seg - Sex: 9h às 18h","link":null}],"whatsapp_link":"https://wa.me/5577991005071","whatsapp_text":"Falar no WhatsApp","whatsapp_note":"Resposta em até 2 horas em horário comercial"}'::jsonb, true, 2),

('contato', 'faq', '{"title":"Perguntas Frequentes","description":"Algumas das perguntas mais comuns que recebemos.","items":[{"question":"Qual o prazo médio para desenvolvimento de um projeto?","answer":"O prazo varia de acordo com a complexidade. Projetos simples podem levar de 2 a 4 semanas, enquanto sistemas mais complexos podem levar de 2 a 6 meses."},{"question":"Vocês oferecem suporte após a entrega?","answer":"Sim! Oferecemos pacotes de suporte e manutenção contínua para garantir que sua solução continue funcionando perfeitamente."},{"question":"Como funciona o processo de orçamento?","answer":"Após o primeiro contato, agendamos uma reunião para entender suas necessidades. Em seguida, elaboramos uma proposta detalhada com escopo, prazo e investimento."},{"question":"Vocês trabalham com projetos de qualquer tamanho?","answer":"Sim! Atendemos desde startups até grandes corporações, adaptando nossas soluções às necessidades e orçamento de cada cliente."}]}'::jsonb, true, 3),

-- CONSULTORIA
('consultoria', 'hero', '{"badge":"Consultoria Especializada","title_line1":"Ciência de Dados &","title_line2":"Inteligência Estratégica","description":"Transformamos dados complexos em decisões estratégicas através de metodologias científicas e análises rigorosas.","cta_primary_text":"Agendar Reunião","cta_primary_link":"/contato","cta_secondary_text":"Ver Especializações","stats":[{"value":"7","label":"Especializações"},{"value":"Multidisciplinar","label":"Equipe"}]}'::jsonb, true, 1),

('consultoria', 'services', '{"title":"Nossas Especializações","description":"Soluções completas em inteligência de dados para empresas que buscam resultados mensuráveis e vantagem competitiva.","items":[{"id":"data-science","title":"Machine Learning & IA","subtitle":"Modelos Preditivos • IA Generativa • MLOps","description":"Desenvolvimento e deploy de modelos de machine learning em produção, desde a prototipagem até a operacionalização escalável.","link":"/consultoria/data-science"},{"id":"bioestatistica","title":"Bioestatística","subtitle":"Ensaios Clínicos • Epidemiologia • Regulatório","description":"Rigor científico em análises estatísticas para saúde, pesquisa clínica e submissões regulatórias.","link":"/consultoria/bioestatistica"},{"id":"behavioral","title":"Análise Comportamental","subtitle":"Vieses Cognitivos • Psicometria • Decisão","description":"Entenda como o comportamento humano impacta seus dados e descubra insights além da estatística tradicional.","link":"/consultoria/behavioral"},{"id":"analytics","title":"Analytics & BI","subtitle":"Dashboards • Visualização • Self-Service","description":"Dashboards estratégicos, automação de relatórios e cultura de dados para tomada de decisão ágil.","link":"/consultoria/analytics"},{"id":"planejamento","title":"Planejamento Estratégico","subtitle":"OKRs • BSC • Roadmaps","description":"Planejamento estratégico orientado por evidências, com metodologias comprovadas e métricas claras.","link":"/consultoria/planejamento"},{"id":"people","title":"People Analytics","subtitle":"RH Estratégico • Turnover • Engajamento","description":"Inteligência de capital humano: predição de turnover, análise de clima e otimização de gestão de pessoas.","link":"/consultoria/people-analytics"},{"id":"customer","title":"Customer Intelligence","subtitle":"CDP • LTV • Churn Prediction","description":"Visão 360° do cliente: segmentação avançada, lifetime value e predição de churn para retenção inteligente.","link":"/consultoria/customer-intelligence"}]}'::jsonb, true, 2),

('consultoria', 'differentials', '{"title":"Por que escolher a Vixio?","description":"Combinamos expertise técnica com visão de negócio para entregar soluções que geram impacto real e mensurável.","items":[{"text":"Metodologia científica rigorosa"},{"text":"Equipe multidisciplinar especializada"},{"text":"Atendimento corporativo dedicado"},{"text":"Resultados mensuráveis garantidos"}],"cta_badge":"100% Sigiloso","cta_title":"Precisa de uma análise personalizada?","cta_description":"Nossa equipe de especialistas está pronta para entender seu desafio e propor soluções baseadas em evidências científicas.","cta_primary_text":"Agendar Consultoria","cta_primary_link":"/contato","cta_secondary_text":"Voltar ao Início","cta_secondary_link":"/"}'::jsonb, true, 3),

-- FUNDADOR
('fundador', 'hero', '{"badge":"CEO & Fundador","name":"Dr. Stenio Fernando","name_highlight":"Pimentel Duarte","subtitle":"Ph.D. em Fisiologia e Fisiopatologia Clínica e Experimental","description":"Cientista, gestor e empreendedor com mais de 20 anos de experiência em pesquisa, ensino e gestão estratégica. Combina rigor científico com visão executiva para transformar dados em decisões que impactam vidas.","stats":[{"value":"20+","label":"Anos de Experiência"},{"value":"100+","label":"Artigos Científicos"}],"lattes_url":"http://lattes.cnpq.br/5318656227506357","linkedin_url":"https://www.linkedin.com/in/stenio-fernando-duarte-b58b8bb0/"}'::jsonb, true, 1),

('fundador', 'quote', '{"text":"Transformar dados em decisões que salvam vidas e impulsionam negócios é mais do que uma profissão — é uma vocação.","author":"Dr. Stenio Fernando Pimentel Duarte"}'::jsonb, true, 2),

('fundador', 'achievements', '{"badge":"Reconhecimento","title":"Conquistas e ","title_highlight":"Impacto","description":"Uma trajetória marcada por contribuições significativas para a ciência, saúde pública e gestão estratégica.","items":[{"value":"100+","label":"Artigos Científicos","description":"Publicações em revistas nacionais e internacionais"},{"value":"Doutor Honoris Causa","label":"Título Honorífico","description":"Reconhecimento pelas contribuições ao progresso das Ciências"},{"value":"Cidadão Conquistense","label":"Título de Honra","description":"Pelo destaque dado à Vitória da Conquista durante a pandemia"},{"value":"4º Melhor","label":"Indicador de Letalidade","description":"Entre as 100 maiores cidades do Brasil durante a COVID-19"}]}'::jsonb, true, 3);
