// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvjjyfnzmspfgqrgkbhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2amp5Zm56bXNwZmdxcmdrYmh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1NzAzNDksImV4cCI6MjA4NDE0NjM0OX0.Gp5hmp9Yc1n2lh_F7RKFJixy-r5D8ykOCnk1IAvqi7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});